### ISSUE TITLE
PlayerPing on v1.11 "

### ISSUE THREAD

**Issue by Ekzim** [ImagineCraft/PlayerPing#2]
[03:46:54] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f950f8e-b64d852 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

[03:50:38] [Server thread/INFO]: Ekzim issued server command: /ping
[03:50:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ping' in plugin PlayerPing v1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_10_R1/entity/CraftPlayer
	at com.cyber.ping.PlayerPing.getPing(PlayerPing.java:43) ~[?:?]
	at com.cyber.ping.PlayerPing.onCommand(PlayerPing.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at com.cyber.ping.PlayerPing.getPing(PlayerPing.java:43) ~[?:?]
	at com.cyber.ping.PlayerPing.onCommand(PlayerPing.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	... 15 more

**Comment by ghost** [comment]
Hello, Ekzim. This is already resolved :)

https://github.com/ImagineCraft/PlayerPing/releases/tag/2.0.0
